### ISSUE TITLE
Eraser functionality

### ISSUE THREAD

**Issue by talapadi** [chimple/tahiti#14]
_From @talapadi on July 24, 2018 14:57_

Any drawings should get erased. The pattern should be saved into json

_Copied from original issue: chimple/maui#639_

**Comment by anandb5** [comment]
**Given**: User should be on the application.
And: Drawing something on the screen.
And: the user required to erase the drawing.
**When:** User selects the eraser with the desired size.
**Then**: The drawing should get erased according to his hand moment
