### ISSUE TITLE
Activity screen in portrait

### ISSUE THREAD

**Issue by talapadi** [chimple/tahiti#2]
_From @talapadi on July 24, 2018 14:15_

The activity screen should have a square area where the child can draw, place photos, stickers, text, attach audio and animations
Below there should be choice of:
- stickers
- pencil tool
- camera/mike
- text

_Copied from original issue: chimple/maui#627_

**Comment by deonchimple** [comment]
**Given**: The user is in-application
**And**: The user is in the activity area
**When**: The user draws, places photos, stickers, text, attach audio or animations
**Then**: The subsequent actions should be performed

**Comment by deonchimple** [comment]
Given: The user is in-application
When: The user enters the activity area
Then: There should options like stickers, pencil tool, camera/mic, text
