### ISSUE TITLE
Tab to choose the tool in activity

### ISSUE THREAD

**Issue by talapadi** [chimple/tahiti#3]
_From @talapadi on July 24, 2018 14:35_

The tab below should display the following:
- Stickers
  - sticker pack 1
    - sticker 1
    - sticker 2
  - sticker pack 2
  - sticker pack.....
- Draw
  - Pencil
    - Pencil thickness 1
    - Pencil thickness 2
    - Pencil thickness 3
    - Paintbrush thickness 1
    - Paintbrush thickness 2
    - Paintbrush thickness 3
    - Marker thickness 1
    - Marker thickness 2
    - Marker thickness 3
    - Crayon thickness 1
    - Crayon thickness 2
    - Crayon thickness 3 
  -Roller
    - Plain Color
    - Background 1
    - Background 2
  - Bucket
    - Pain color
    - Background 1
    - Background 2
  - Eraser
    - Thickness 1
    - Thickness 2
- Video/Picture/Mike
  - Take Picture 
  - Use picture from gallery
  - Take video
  - Record from mike
- Text

_Copied from original issue: chimple/maui#628_

**Comment by deonchimple** [comment]
**Given**: The user is in-application
**And**: The user is in the activity area
**When**: The user clicks on the tab
**Then**: The tab shows options and relevant sub options.
