### ISSUE TITLE
Place an image template in the activity area

### ISSUE THREAD

**Issue by talapadi** [chimple/tahiti#5]
_From @talapadi on July 24, 2018 14:48_

An image should be placed in the activity area. Over this image, other actions such as stickers, drawings should be placed.

_Copied from original issue: chimple/maui#630_

**Comment by deonchimple** [comment]
**Given**: The user is in the application
**And**: User uses the activity area
**When**: The user selects an image
**Then**: The image is placed onto the activity area.

**Comment by deonchimple** [comment]
**Given**: The user is in the application
**And**: User uses the activity area
**When**: The user selects an image
**Then**: The image is placed onto the activity area.
